module.exports = {
	API_REQUEST: "API_REQUEST",
	SUMMONER_FOUND: "SUMMONER_FOUND",
	SUMMONER_SEARCH_ERROR: "SUMMONER_SEARCH_ERROR",
	GAMES_FOUND: "GAMES_FOUND",
	GAMES_SEARCH_ERROR: "GAMES_SEARCH_ERROR",
	GAMES_CLEAN_UP: "GAMES_CLEAN_UP",
	REGIONALS_FOUND: "REGIONALS_FOUND",
	REGIONALS_ERROR: "REGIONALS_ERROR",
	LOL_STATIC_BASE_URL: "http://ddragon.leagueoflegends.com/cdn",
	LOL_API_VERSION:"6.7.1",
	MILLISECONDS: 1000,
	DOUBLE_KILL: "DOUBLE KILL",
	TRIPLE_KILL: "TRIPLE KILL",
	QUADRA_KILL: "QUARDA KILL",
	PENTA_KILL: "PENTA KILL",
	SINGLE_KILL: "NONE"
};