module.exports = {
	API_REQUEST: "API_REQUEST",
	SUMMONER_FOUND: "SUMMONER_FOUND",
	SUMMONER_SEARCH_ERROR: "SUMMONER_SEARCH_ERROR",
	GAMES_FOUND: "GAMES_FOUND",
	GAMES_SEARCH_ERROR: "GAMES_SEARCH_ERROR"
};