module.exports = {
	API_REQUEST: "API_REQUEST",
	SUMMONER_FOUND: "SUMMONER_FOUND",
	SUMMONER_SEARCH_ERROR: "SUMMONER_SEARCH_ERROR",
	SUMMONER_CHANGE_REGION: "SUMMONER_CHANGE_REGION",
	SUMMONER_CHANGE_SUMMONER: "SUMMONER_CHANGE_SUMMONER",
	SUMMONER_CHANGE_QRYLEN: "SUMMONER_CHANGE_QRYLEN",
	SUMMONER_CHANGE_ARROWNAV: "SUMMONER_CHANGE_ARROWNAV",
	SUMMONER_RESET: "SUMMONER_RESET",
	GAMES_FOUND: "GAMES_FOUND",
	GAMES_SEARCH_ERROR: "GAMES_SEARCH_ERROR",
	GAMES_CLEAN_UP: "GAMES_CLEAN_UP",
	REGIONALS_FOUND: "REGIONALS_FOUND",
	REGIONALS_ERROR: "REGIONALS_ERROR",
	LOL_STATIC_BASE_URL: "http://ddragon.leagueoflegends.com/cdn",
	LOL_API_VERSION:"6.7.1",
	DOUBLE_KILL: "DOUBLE KILL",
	TRIPLE_KILL: "TRIPLE KILL",
	QUADRA_KILL: "QUADRA KILL",
	PENTA_KILL: "PENTA KILL",
	SINGLE_KILL: "NONE",
	DAMAGE_PHYSICAL: "Physical damage",
	DAMAGE_MAGIC: "Magic damage",
	DAMAGE_TRUE: "True damage",
	DEFAULT_SUMMONER_ICON_PATH: "/images/default_profile_icon.png",
	SEARCH_REGION_OPTIONS: [
		{
			description: "EUW",
			short: "euw"
		},
		{
			description: "EUNE",
			short: "eune"
		},
		{
			description: "NA",
			short: "na"
		},
		{
			description: "KR",
			short: "kr"
		},
		{
			description: "CN",
			short: "cn"
		},
		{
			description: "LAN",
			short: "lan"
		}
	],
	QUERY_MIN_LENGTH: 2
};